version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      - "22"
  nimbus:
    image: registry.steelhouse.com/storm-nimbus:1.0.1
    ports:
      - "3773:3773"
      - "3772:3772"
      - "6627:6627"
      - "22"
    environment:
      NIMBUS_PORT_6627_TCP_ADDR: nimbus
      ZK_PORT_2181_TCP_ADDR: zk
    links:
      - zookeeper:zk
  supervisor:
    image: registry.steelhouse.com/storm-supervisor:1.0.1
    ports:
      - "8000"
      - "22"
    environment:
      NIMBUS_PORT_6627_TCP_ADDR: nimbus
      ZK_PORT_2181_TCP_ADDR: zk
    links:
      - nimbus:nimbus
      - zookeeper:zk
  ui:
    image: registry.steelhouse.com/storm-ui:1.0.1
    ports:
      - "8080:8080"
      - "22"
    environment:
      NIMBUS_PORT_6627_TCP_ADDR: nimbus
      ZK_PORT_2181_TCP_ADDR: zk
    links:
      - nimbus:nimbus
      - zookeeper:zk